export const SET_USER = 'SET_USER'

export const REMOVE_USER = 'REMOVE_USER'

export const EDIT_USER = 'EDIT_USER'

export const ADD_AUTH_APPLICATION = 'ADD_AUTH_APPLICATION'

export const SET_USER_SUBSCRIBE = 'SET_USER_SUBSCRIBE'

export const DELETE_AUTH_APPLICATION = 'DELETE_AUTH_APPLICATION'

export const ADD_AUTH_COMMENT = 'ADD_COMMENT'

export const DELETE_AUTH_COMMENT = 'DELETE_COMMENT'
